export { equals } from "./equals.js"

export { getType } from "./getType.js"
export { is } from "./is.js"
export { isSame } from "./isSame.js"
export { isSameType } from "./isSameType.js"
export { isTruthy } from "./isTruthy.js"
export { isNil } from "./isNil.js"
export { isFunction } from "./isFunction.js"
export { isDate } from "./isDate.js"
export { isIterable } from "./isIterable.js"
export { isSetoid } from "./isSetoid.js"

export { inspect } from "./inspect.js"
export { nodeInspect } from "./nodeInspect.js"
